services:
  openldap:
    image: osixia/openldap:1.5.0
    container_name: directory-lab-openldap
    environment:
      LDAP_TLS: "false"
      # LDAP_TLS_ENFORCE: "false"
      LDAP_ORGANISATION: "Directory Lab"
      LDAP_DOMAIN: "example.org"
      # replication off
      LDAP_REPLICATION: "false"
      LDAP_ADMIN_PASSWORD: "adminpassword"
      # Optional: enable verbose logs while learning
      LDAP_LOG_LEVEL: "256"
    ports:
      - "389:389"   # LDAP
      - "636:636"   # LDAPS
    volumes:
      - ./ldif/bootstrap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/50-bootstrap.ldif
    command: --copy-service
    restart: unless-stopped

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: directory-lab-phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"  # keep simple for local lab
    ports:
      - "18081:80"
    depends_on:
      - openldap
    restart: unless-stopped

volumes:
  openldap_data:
  openldap_config:
